---
title: "Coverage"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, error=TRUE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(rlang)
library(scales)
library(DT)

```

<br> 

```{r , echo = FALSE, message = FALSE}

### read files

## harmonized data file
detailed <- read_rds("./detailed_data/03_intermediate/gaps_filled.rds")

# sheets from detailed data
general <- detailed$general
sheet_min <- detailed$minerals_ores_conce
sheet_com <- detailed$commodities


## national accounts

# get the latest file for national accounts from folder
source("./detailed_data/02_scripts/functions/lastfile.R")

lastfile <- my_lastfile("./detailed_data/01_input/05_other_data/", "data_converted")

nat_acc <- read_rds(lastfile)

# nat_acc <- read_delim(
#   lastfile, 
#   delim = ";", 
#   col_types = cols(year = "i", unit_id = "c")
#   )


## IDs
mat_ids <- read_delim("./detailed_data/01_input/02_lists_and_concordance_tables/material_ids.csv", delim = ";")

source_ids <- read_delim("./detailed_data/01_input/02_lists_and_concordance_tables/source_ids.csv", delim = ";")

```

<br> 

#### General coverage

```{r , echo = FALSE, message = FALSE}

# general coverage

if(exists("gen_cov")) rm(gen_cov)

gen_cov <- tibble(Indicator = NA, Amount = NA) %>% 
  filter(!is.na(Amount)) %>%
  mutate(Indicator = as.character(Indicator), Amount = as.numeric(Amount))

gen_cov <- gen_cov %>%
  union(., tibble(
    Indicator = "Number of countries",
    Amount = general %>% distinct(country) %>% nrow()
  )) %>%
  union(., tibble(
    Indicator = "Number of mines / processing facilities",
    Amount = general %>% distinct(mine_fac) %>% nrow()
  )) %>%
  union(., tibble(
    Indicator = "Number of materials (w/o processing)",
    Amount = (sheet_min %>% distinct(min_ore_con) %>% nrow()) +
      (sheet_com %>% distinct(commodity) %>% nrow())
  )) %>%
  union(., tibble(
    Indicator = "Number of years",
    Amount = length(union(sheet_min$year, sheet_com$year))
  )) %>%
  union(., tibble(
    Indicator = "Number of grades",
    Amount = sheet_com %>% filter(!is.na(grade)) %>% nrow()
  )) %>%
  union(., tibble(
    Indicator = "Number of yields",
    Amount = sheet_com %>% filter(!is.na(yield)) %>% nrow()
  )) %>%
  union(., tibble(
    Indicator = "Number of recovery rates",
    Amount = sheet_com %>% filter(!is.na(recovery_rate)) %>% nrow()
  )) %>%
  union(., tibble(
    Indicator = "Number of sources",
    Amount = source_ids %>% nrow()
  ))



# table for Rmd output
datatable(gen_cov, rownames = FALSE, caption = "General coverage")



# number of mines/facilities by type
nr_min_fac <- general %>%
  group_by(mine_or_processing) %>%
  summarise(n = n())

# table for Rmd output
datatable(nr_min_fac, rownames = FALSE, caption = "Number of mines/facilities by type")



# nr of materials per category
nr_mat_by_cat <- sheet_min %>%
  distinct(min_ore_con) %>%
  rename(material_id = min_ore_con) %>%
  union(.,
        sheet_com %>%
          distinct(commodity) %>%
          rename(material_id = commodity)
  ) %>%
  filter(!is.na(material_id)) %>%
  left_join(.,
    mat_ids %>% select(material_category, material_category_2, material_id)
  ) %>%
  group_by(material_category, material_category_2) %>%
  summarise(n = n())

# table for Rmd output
datatable(nr_mat_by_cat, rownames = FALSE, caption = "Number of materials per category")



# nr of mines/facilities per country

nr_min_fac_by_cou <- general %>%
  group_by(alphanumiso) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
  
# table for Rmd output
datatable(nr_min_fac_by_cou, rownames = FALSE, caption = "Number of mines per country")


# graphic for Rmd output
ggplot(data = head(nr_min_fac_by_cou), aes(x = reorder(alphanumiso, -n), y = n)) + 
  geom_bar(stat = "identity", fill = "steelblue") + 
  geom_text(aes(label = n), vjust = 1.6, color = "white", size = 3.5)+
  labs(x = "Country", y = "No. of Mines")

  
# nr of materials per country

nr_mat_by_cou <- sheet_min %>%
  distinct(mine_fac, min_ore_con) %>%
  rename(material_id = min_ore_con) %>%
  union(.,
        sheet_com %>%
          distinct(mine_fac, commodity) %>%
          rename(material_id = commodity)
        ) %>%
  left_join(.,
            general %>%
              select(mine_fac, alphanumiso)
            ) %>%
  distinct(material_id, alphanumiso) %>%
  group_by(alphanumiso) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

# table for Rmd output
datatable(nr_mat_by_cou, rownames = FALSE, caption = "Number of materials per country")



# nr of mines per material (processing not included)

nr_mine_by_mat <- sheet_min %>%
  distinct(mine_fac, min_ore_con) %>%
  rename(material_id = min_ore_con) %>%
  union(.,
        sheet_com %>%
          distinct(mine_fac, commodity) %>%
          rename(material_id = commodity)
        ) %>%
  distinct(material_id, mine_fac) %>%
  group_by(material_id) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

# table for Rmd output
datatable(nr_mine_by_mat, rownames = FALSE, caption = "Number of mines per material")
```

<br> 


```{r , echo = FALSE, message = FALSE}
# graphic for Rmd output
nr_mine_by_mat_plot <- left_join(nr_mine_by_mat, select(mat_ids, material_id, material_name), by = "material_id")
nr_mine_by_mat_plot$material_name <- coalesce(nr_mine_by_mat_plot$material_name, nr_mine_by_mat_plot$material_id)
nr_mine_by_mat_plot <- nr_mine_by_mat_plot %>% mutate(material_name = replace(material_name, material_name == "F.stc", "Steam coal"))

ggplot(data = head(nr_mine_by_mat_plot), aes(x = reorder(material_name, -n), y = n)) + 
  geom_bar(stat = "identity", fill = "steelblue") + 
  geom_text(aes(label = n), vjust = 1.6, color = "white", size = 3.5)+
  labs(x = "Material", y = "No. of Mines") 
```

<br> 

#### Commodities

```{r , echo = FALSE, message = FALSE}

# include country_ids in sheet_com
agg_com <- sheet_com %>%
  left_join(.,
            detailed$general %>%
              distinct(mine_fac, alphanumiso) %>%
              mutate(alphanumiso = ifelse(is.na(alphanumiso), "Other", alphanumiso))
            )



# aggregate 
agg_com <- agg_com %>%
  group_by(alphanumiso, commodity, year) %>%
  summarise(value = sum(value, na.rm = TRUE)) %>%
  ungroup()



# join with national accounts
agg_com <- agg_com %>%
  left_join(.,
            nat_acc %>% select(alphanumiso, material_id, year, value),
            by = c("alphanumiso", "commodity" = "material_id", "year"),
            suffix = c(".det", ".nat")
            )


# data rows without allocation
not_incl_com <- agg_com %>%
  filter(
    !(year %in% c(2018, 2019)),
    is.na(alphanumiso) |
    is.na(commodity) |
    is.na(value.nat)
    ) %>%
  group_by(commodity) %>%
  summarise(n = n())


# share
agg_com <- agg_com %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2)
    )

# clean table
agg_com <- agg_com %>%
  filter(
    !(year %in% c(2018, 2019)),
    !is.na(alphanumiso),
    !is.na(commodity),
    !is.na(value.nat)
    )



# spread by country_id and material_id
com_cov1 <- agg_com %>%
  mutate(share = percent(share, accuracy = 1)) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year)) %>%
  pivot_wider(., names_from = year, values_from = share) %>%
  arrange(commodity) %>%
  # insert national totals again in order to rank properly (couldn't be kept, because of pivot function)
  left_join(., agg_com %>% filter(year == 2015) %>% select(-value.det, -share, -year)) %>%
  arrange(commodity, desc(value.nat))

# table for Rmd output
datatable(com_cov1, rownames = FALSE, caption = "Relative coverage by material and country")




## coverages >100%

# sheet_com with alphanumiso
sheet_com_cou <- sheet_com %>%
      left_join(.,
                detailed$general %>%
                  distinct(mine_fac, alphanumiso) %>%
                  mutate(alphanumiso = ifelse(is.na(alphanumiso), "Other", alphanumiso))
                ) %>%
      select(alphanumiso, commodity, year, mine_fac, value) %>%
  group_by(alphanumiso, commodity, year, mine_fac) %>%
  summarise(value = sum(value)) %>%
  ungroup()


# filter for shares >100%
exc_cov <- agg_com %>%
  filter(share > 1) %>%
  mutate(share = percent(share, accuracy = 1)) %>%
  mutate(
    `Abs. diff larger than nat. value` = value.det - value.nat,
    unit = "Kt") %>%
  arrange(alphanumiso, commodity, year)


# select "responsible" mines
exc_cov_mines <- exc_cov %>%
  select(alphanumiso, commodity, year) %>%
  left_join(., 
            sheet_com_cou %>% select(alphanumiso, commodity, year, mine_fac, value)
            ) %>%
  arrange(alphanumiso, commodity, year, desc(value))


# use tempory tibble and loop to get respective mines into one string
  # (shorter options didn't work somehow)

temp_t <- tibble(alphanumiso = "chr", commodity = "chr", year = 1, mines = "chr") %>% 
  filter(mines != "chr")

for (i in 1:nrow(exc_cov)) {
  
  a <- exc_cov[i,] %>% select(alphanumiso, commodity, year)
  
  mine_str <- a %>%
    left_join(exc_cov_mines) %>%
    distinct(mine_fac) %>%
    pull() %>%
    paste0(collapse = ", ")
  
  temp_t <- temp_t %>%
    union(., a %>% mutate(mines = mine_str))
  
}

exc_cov <- exc_cov %>%
  left_join(., temp_t)


# table for Rmd output
datatable(exc_cov, rownames = FALSE, caption = "Coverages which are >100% for commodities_sheet")




# spread by global totals for material_ids
com_cov2 <- agg_com %>%
  group_by(commodity, year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2),
    share = percent(share, accuracy = 1)
  ) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year)) %>%
  pivot_wider(., names_from = year, values_from = share) %>%
  arrange(commodity)


# table for Rmd output
datatable(com_cov2, rownames = FALSE, caption = "Relative coverage of global total by material")


```

<br> 

#### Ores and non-metallic minerals

```{r , echo = FALSE, message = FALSE}

# include country_ids in sheet_min
agg_min <- sheet_min %>%
  left_join(.,
            detailed$general %>%
              distinct(mine_fac, alphanumiso) %>%
              mutate(alphanumiso = ifelse(is.na(alphanumiso), "Other", alphanumiso))
  )



# aggregate 
agg_min <- agg_min %>%
  filter(!(type_mineral %in% c("Ore mined", "Coal mined"))) %>%
  filter(!is.na(min_ore_con)) %>%
  group_by(alphanumiso, type_mineral, min_ore_con, year) %>%
  summarise(value = sum(value, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-type_mineral)




# join with national accounts
agg_min <- agg_min %>%
  left_join(.,
            nat_acc %>% select(alphanumiso, material_id, year, value),
            by = c("alphanumiso", "min_ore_con" = "material_id", "year"),
            suffix = c(".det", ".nat")
  )


# data rows without allocation
not_incl_min <- agg_min %>%
  filter(
    !(year %in% c(2018, 2019)),
    is.na(alphanumiso) |
    is.na(min_ore_con) |
    is.na(value.nat)
    ) %>%
  group_by(min_ore_con) %>%
  summarise(n = n())


# share
agg_min <- agg_min %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2)
  )


# clean table
agg_min <- agg_min %>%
  filter(
    !(year %in% c(2018, 2019)),
    !is.na(alphanumiso),
    !is.na(min_ore_con),
    !is.na(value.nat),
  )



# spread by country_id and material_id
min_cov1 <- agg_min %>%
  mutate(share = percent(share, accuracy = 1)) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year)) %>%
  pivot_wider(., names_from = year, values_from = share) %>%
  arrange(min_ore_con) %>%
  # insert national totals again in order to rank properly (couldn't be kept, because of pivot function)
  left_join(., agg_min %>% filter(year == 2015) %>% select(-value.det, -share, -year)) %>%
  arrange(min_ore_con, desc(value.nat))

# table for Rmd output
datatable(min_cov1, rownames = FALSE, caption = "Relative coverage by material and country")



## coverages >100%

# sheet_min with alphanumiso
sheet_min_cou <- sheet_min %>%
  filter(!(type_mineral %in% c("Ore mined", "Coal mined"))) %>%
      left_join(.,
                detailed$general %>%
                  distinct(mine_fac, alphanumiso) %>%
                  mutate(alphanumiso = ifelse(is.na(alphanumiso), "Other", alphanumiso))
                ) %>%
      select(alphanumiso, min_ore_con, year, mine_fac, value) %>%
  group_by(alphanumiso, min_ore_con, year, mine_fac) %>%
  summarise(value = sum(value)) %>%
  ungroup()

# filter for shares >100%
exc_cov <- agg_min %>%
  filter(share > 1) %>%
  mutate(share = percent(share, accuracy = 1)) %>%
  mutate(
    `Abs. diff larger than nat. value` = value.det - value.nat,
    unit = "Kt") %>%
  arrange(alphanumiso, min_ore_con, year)

# select "responsible" mines
exc_cov_mines <- exc_cov %>%
  select(alphanumiso, min_ore_con, year) %>%
  left_join(., 
            sheet_min_cou %>% select(alphanumiso, min_ore_con, year, mine_fac, value)
            ) %>%
  arrange(alphanumiso, min_ore_con, year, desc(value))


# use tempory tibble and loop to get respective mines into one string
  # (shorter options didn't work somehow)

temp_t <- tibble(alphanumiso = "chr", min_ore_con = "chr", year = 1, mines = "chr") %>% 
  filter(mines != "chr")

for (i in 1:nrow(exc_cov)) {
  
  a <- exc_cov[i,] %>% select(alphanumiso, min_ore_con, year)
  
  mine_str <- a %>%
    left_join(exc_cov_mines) %>%
    distinct(mine_fac) %>%
    pull() %>%
    paste0(collapse = ", ")
  
  temp_t <- temp_t %>%
    union(., a %>% mutate(mines = mine_str))
  
}

exc_cov <- exc_cov %>%
  left_join(., temp_t)

# table for Rmd output
datatable(exc_cov, rownames = FALSE, caption = "Coverages which are >100% for minerals_sheet")



# spread by global totals for material_ids
min_cov2 <- agg_min %>%
  group_by(min_ore_con, year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2),
    share = percent(share, accuracy = 1)
  ) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year)) %>%
  pivot_wider(., names_from = year, values_from = share) %>%
  arrange(min_ore_con)

# table for Rmd output
datatable(min_cov2, rownames = FALSE, caption = "Relative coverage of global total by material")


```

<br>

### Global coverages figures
```{r , echo = FALSE, message = FALSE}
### Global coverages ### 
# create table with global coverage of selected commodities and minerals 

# get global coverage of minerals
min_cov_plot <- agg_min %>%
  group_by(min_ore_con, year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2),
  ) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year))

# get global coverage of commodities
com_cov_plot <- agg_com %>%
  group_by(commodity, year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2),
  ) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year))


# combine the two dataframes
cov_plot <- bind_rows(com_cov_plot, min_cov_plot)
cov_plot$min_ore_con <- coalesce(cov_plot$min_ore_con , cov_plot$commodity)
cov_plot <- left_join(cov_plot, select(mat_ids, material_id, material_name),
                      by = c("min_ore_con" = "material_id"))

#clean
cov_plot <- cov_plot %>% 
  select(-commodity)  %>% 
  filter(year > 1999)


# select which materials should be displayed
# unique(cov_plot$min_ore_con)
cov_plot_materials <- filter(cov_plot, min_ore_con %in% c("Me.Ag", "Me.Au",
                                                       "Me.Cu", "Me.Mo", "Me.Ni", "Me.Pb", "Me.Zn", "Me.Co",  "Me.Sn", 
                                                       "Me.Pd", "Me.Pt", "Me.Rh",
                                                       "O.Al", "O.Fe")) #most materials

ggplot(cov_plot_materials, aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

# create a line chart of the coverage of selected commodities and minerals groups only
cov_plot_group1 <- filter(cov_plot, min_ore_con %in% c("Me.Ag", "Me.Au", "Me.Cu", "Me.Mo")) #gold, silver
cov_plot_group2 <- filter(cov_plot, min_ore_con %in% c("Me.Ni", "Me.Pb", "Me.Zn", "Me.Co")) #poly-metallic
cov_plot_group3 <- filter(cov_plot, min_ore_con %in% c("Me.Pd", "Me.Pt", "Me.Rh", "Me.Sn", "Me.Te")) #PGM 
cov_plot_group4 <- filter(cov_plot, min_ore_con %in% c("O.Al", "O.Fe")) #Ores

# group 1
ggplot(cov_plot_group1, aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

# group 2
ggplot(cov_plot_group2, aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") +
  ylim(0, 1)

# group 3
ggplot(cov_plot_group3, aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") +
  ylim(0, 1)

# group 4
ggplot(cov_plot_group4, aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") +
  ylim(0, 1)


### National Coverages ### 

# combine the two dataframes (minerals and commodities)
cov_plot_national <- bind_rows(agg_com, agg_min)
cov_plot_national$min_ore_con <- coalesce(cov_plot_national$min_ore_con , cov_plot_national$commodity)
cov_plot_national <- left_join(cov_plot_national, select(mat_ids, material_id, material_name),
                      by = c("min_ore_con" = "material_id"))

#clean and filter for only the top commodities copper, iron ore, bauxite
cov_plot_national <- cov_plot_national %>% 
  select(-commodity)  %>% 
  filter(year > 1999) %>% 
  filter(min_ore_con %in% c("Me.Cu", "O.Fe", "O.Al"))

```


<br>

### National coverages figures

```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage USA"}
#USA
ggplot(filter(cov_plot_national, alphanumiso == "USA840"), aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

```

```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage Australia"}
#Australia
ggplot(filter(cov_plot_national, alphanumiso == "AUS036"), aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

```

```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage China"}
#China
ggplot(filter(cov_plot_national, alphanumiso == "CHN156"), aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

```

```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage Brazil"}
#Brazil
ggplot(filter(cov_plot_national, alphanumiso == "BRA076"), aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

```

```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage South Africa"}
#South Africa
ggplot(filter(cov_plot_national, alphanumiso == "ZAF710"), aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

```

```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage Chile"}
#Chile
ggplot(filter(cov_plot_national, alphanumiso == "CHL152"), aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)
  
```

```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage Peru"}
#Peru
ggplot(filter(cov_plot_national, alphanumiso == "PER604"), aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

```

<br> 

#### Data rows not included in coverage

```{r , echo = FALSE}
# tables have been compiled above before cleaning NAs

# table for Rmd output
datatable(not_incl_com, rownames = FALSE, caption = "Number of data rows not included by commodity")

# table for Rmd output
datatable(not_incl_min, rownames = FALSE, caption = "Number of data rows not included by mineral/ore")

```

