---
title: "Compile estimation factors"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup , include = FALSE, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(scales)
library(grid)
library(knitr)
library(kableExtra)
library(viridis)

```



```{r , echo = FALSE, message = FALSE}
## read files
# harmonized data file
detailed <- read_rds("./detailed_data/03_intermediate/gaps_filled.rds")

# list of columns
sheets_columns <- read_delim("./detailed_data/01_input/02_lists_and_concordance_tables/sheets_columns.csv", delim = ";")

# metal prices
met_price <- read_delim("./detailed_data/01_input/05_other_data/average_prices_1990-2020.csv", delim = ";")

# sheets
sheet_com <- detailed$commodities
sheet_min <- detailed$minerals_ores_conce


```

<br> 

```{r , echo = FALSE, message = FALSE}
## include other variables

# countries
sheet_all <- sheet_com %>%
  left_join(.,
            detailed$general %>%
              distinct(mine_fac, alphanumiso) %>%
              mutate(alphanumiso = ifelse(is.na(alphanumiso), "Other", alphanumiso))
  )

# prices
sheet_all <- sheet_all %>%
  left_join(.,
            met_price %>% select(material_id, average_price),
            by = c("commodity" = "material_id")
  )

# ores
sheet_all <- sheet_all %>%
  left_join(.,
            sheet_min %>% 
              filter(type_mineral %in% c("Ore processed")) %>%
              select(mine_fac, min_ore_con, year, value),
            by = c("mine_fac", "min_ore_con", "year"),
            suffix = c(".com", ".min")
  )



## Calculate stuff

# Calculate value of metal
sheet_all <- sheet_all %>%
  mutate(met_value = value.com * 1000 * average_price) # taking into account proper units: i.e. t vs USD/kg

# Calculating total value per ore, join that into table
sheet_all <- sheet_all %>%
  left_join(
    sheet_all %>%
      group_by(mine_fac, min_ore_con, year) %>%
      summarise(total_met_value = sum(met_value))
  )

# Calculate ratio (t/t) of ore per metal (i.e. share of metal value per ore value times amount of ore, and then "ore share" per amount of metal)
sheet_all <- sheet_all %>%
  mutate(ore_share = (met_value / total_met_value * value.min)) %>%
  mutate(ratio_ore_per_met = ore_share / value.com)



# Consolidate by country, i.e. group by country and summarize ore ratio with weighted average (weighted by amount of metal)
est_fac <- sheet_all %>%
  group_by(alphanumiso, commodity, year) %>%
  summarise(ratio_ore_per_met = weighted.mean(ratio_ore_per_met, value.com, na.rm = TRUE)) %>%
  ungroup()



# Remove everything without a ratio (e.g. commodities like alloys or just years lacking data)
est_fac <- est_fac %>%
  filter(!is.na(ratio_ore_per_met))


```

<br> 

#### Line charts with time series for each commodity

```{r , echo = FALSE, message = FALSE, warning = FALSE}

# Line charts for checking time series

list_comm <- est_fac %>% filter(!is.na(commodity)) %>% distinct(commodity) %>% arrange(commodity) %>% pull()
i <- "Me.Ag"
a <- list()
for (i in list_comm) {

  nr_colour <- nrow(est_fac %>% filter(commodity == i) %>% distinct(alphanumiso))

  # print(
  #   ggplot(
  #     est_fac %>% filter(commodity == i),
  #     aes(x = year, y = ratio_ore_per_met, group = alphanumiso)) +
  #     labs(title = i, y = "Ore-to-metal ratio (t/t)") +
  #     geom_line(aes(color = alphanumiso)) +
  #     scale_color_manual(values=viridis_pal()(nr_colour)) +
  #     scale_y_continuous(
  #       breaks = pretty_breaks(n=6),
  #       expand = c(0, 0)) +
  #     theme_minimal()
  # )


  # a[[i]] <- est_fac %>%
  #     filter(commodity == i) %>%
  #     ggplot2::ggplot(aes(x = year, y = ratio_ore_per_met, color = alphanumiso)) +
  #     ggseas::stat_index(index.ref = 1) +
  #     scale_colour_manual(values=viridis_pal()(nr_colour)) +
  #     theme_minimal() +
  #     theme(
  #       title = element_text(colour="#444444"),
  #       plot.margin = margin(t = 40, b = 30, l = 30),
  #       legend.title = element_blank()
  #     ) +
  #     ggtitle(i) +
  #     xlab("Time") +
  #     ylab("Ore-to-metal ratio (t/t)")
  # 
  #   a[[i]] <- plotly::ggplotly(a[[i]]) %>%
  #     plotly::layout(legend = list(orientation = "v", yanchor = "center", y = 0.5)) %>%
  #     plotly::config(displaylogo = FALSE, modeBarButtonsToRemove = list('toImage')) %>%
  #     htmlwidgets::onRender("function(e1, t){ checkOverlap(); }")


  a[[i]] <- est_fac %>%
    filter(commodity == i) %>%
    plotly::plot_ly(
      x = ~year,
      y = ~ratio_ore_per_met,
      color = ~alphanumiso
      ) %>% 
    plotly::add_lines() %>%
    plotly::layout(title = i)
  
}  
  
  htmltools::tagList(a)



```

<br> 

#### All ratios for each commodity and country compared to overall median/mean of commodity

```{r , echo = FALSE, message = FALSE}

# Create dynamic DT::datatable to show highest and lowest values for estimation factors of each commodity (for error checking)
  # And include difference from median/mean of commodity across all years

  highest_values <- est_fac %>%
    left_join(
      est_fac %>%
        group_by(commodity) %>%
        summarise(
          median_ratio = median(ratio_ore_per_met, na.rm = TRUE),
          mean_ratio = mean(ratio_ore_per_met, na.rm = TRUE)
          ) %>%
        ungroup(),
      by = c("commodity")
      ) %>%
    mutate(
      diff_median_ratio = ratio_ore_per_met / median_ratio,
      diff_mean_ratio = ratio_ore_per_met / mean_ratio
      ) %>%
    arrange(desc(diff_median_ratio))


  # table for Rmd output
DT::datatable(highest_values)  

```


