---
title: "Intermediate data check"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup , include = FALSE, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(rlang)
library(scales)
```

<br> 

```{r , echo = FALSE, message = FALSE}

## read files

## read files
# harmonized and converted data file
detailed <- read_rds("./03_intermediate/01_detailed_data/all_tables_converted.rds")

# list of columns
sheets_columns <- read_delim("./01_input/02_lists_and_concordance_tables/01_detailed_data/sheets_columns.csv", delim = ";")


# sheets
sheet_min <- detailed$minerals_ores_conce
sheet_com <- detailed$commodities

```

<br> 

```{r , echo = FALSE, message = FALSE}
## Add duplicates for "Ore processed" from "Ore mined" and vice versa
  ## These duplicates are only for checking and do not represent the actual duplicates introduced later after aggregation (the main reason being that without prior aggregation the duplicates might potentially create false values, especially due to different sub-sites, different mining types, and different ores) -> However, for this purpose here, it seems appropriate to include it prior aggregation as proxy values without differentiating by sub_site/type_mining/type_mineral, but only mine_fac and year.

ore_mined <- sheet_min %>%
  filter(type_mineral == "Ore mined") %>%
  distinct(mine_fac, year)

ore_proc <- sheet_min %>%
  filter(type_mineral == "Ore processed") %>%
  distinct(mine_fac, year)

# mines with reported ore mined for a year, but no ore processed for that year
mine_list <- setdiff(ore_mined, ore_proc)

sheet_min <- sheet_min %>% 
  union(
    mine_list %>%
      left_join(sheet_min %>% filter(type_mineral == "Ore mined")) %>%
      mutate(type_mineral = "Ore processed")
    )

# mines with reported ore processed, but no ore mined for that year
mine_list <- setdiff(ore_proc, ore_mined)

sheet_min <- sheet_min %>% 
  union(
    mine_list %>%
      left_join(sheet_min %>% filter(type_mineral == "Ore processed")) %>%
      mutate(type_mineral = "Ore mined")
  )

```

<br> 

```{r , echo = FALSE, message = FALSE}
## Add duplicates for "Clean coal" from "Coal mined" and vice versa
  ## Details similar to "Ore processed" and "Ore mined" above

ore_mined <- sheet_min %>%
  filter(type_mineral == "Coal mined") %>%
  distinct(mine_fac, year)

ore_proc <- sheet_min %>%
  filter(type_mineral == "Clean coal") %>%
  distinct(mine_fac, year)

# mines with reported coal mined for a year, but no Clean coal for that year
mine_list <- setdiff(ore_mined, ore_proc)

sheet_min <- sheet_min %>% 
  union(
    mine_list %>%
      left_join(sheet_min %>% filter(type_mineral == "Coal mined")) %>%
      mutate(type_mineral = "Clean coal")
  )

# mines with reported Clean coal, but no coal mined for that year
mine_list <- setdiff(ore_proc, ore_mined)

sheet_min <- sheet_min %>% 
  union(
    mine_list %>%
      left_join(sheet_min %>% filter(type_mineral == "Clean coal")) %>%
      mutate(type_mineral = "Coal mined")
  )

```

<br> 

#### Mines which are in both tables, but are not joined

```{r , echo = FALSE, message = FALSE}
## check which rows from sheet_min would not be included in join of sheet_com, because variables don't fit
 ## based on six variables: mine_fac, sub_site, min_ore_con, type_mining, year, mine_processing

# matching entries
match <- intersect(
  sheet_min %>%
    filter(type_mineral %in% c("Ore processed", "Concentrate") & value != 0) %>%
    select(mine_fac, sub_site, min_ore_con, type_mining, year, mine_processing),
  sheet_com %>%
    select(mine_fac, sub_site, min_ore_con, type_mining, year, mine_processing)
)

# mine_fac which have entries in both sheets for same year, but are not matched
  # excluding those which could be matched
  # returning only the respective entries from sheet_min
non_fit <- intersect(
  setdiff(
    sheet_min %>%
      filter(type_mineral %in% c("Ore processed", "Concentrate") & value != 0) %>%
      select(mine_fac, sub_site, min_ore_con, type_mining, year, mine_processing),
    match
    ) %>%
    select(mine_fac, year),
  setdiff(
    sheet_com %>%
      select(mine_fac, sub_site, min_ore_con, type_mining, year, mine_processing),
    match
    ) %>%
    select(mine_fac, year)
  ) %>%
  left_join(.,
            setdiff(
              sheet_min %>%
                filter(type_mineral %in% c("Ore processed", "Concentrate") & value != 0) %>%
                select(mine_fac, sub_site, min_ore_con, type_mining, year, mine_processing),
              match
              )
            ) %>%
  arrange(mine_fac, desc(year))


# save no_match table as csv
write_delim(non_fit, "./04_output/01_detailed_data/03_intermediate_check/non_fit.csv", delim = ";")

# table for Rmd output
DT::datatable(non_fit)  


# comment: maybe exclude those from sheet_min (just for the check) which are not Oxide ores and at the same time have also a concentrate production reported (e.g. sulphide ore resulting in concentrate) ??? because then content is likely provided for concentrate already


```

<br> 

#### Mines which have the same coordinates in sheet_general and sheet_sub_sites. 

```{r, echo = FALSE, message = FALSE}

### check for double entries of coordinates in sheet_general and sheet_sub_sites

general <- detailed$general
sub_sites <- detailed$sub_sites

#first, create a column "sub_site" which is empty for the sheet general
general <- add_column(general, sub_site = NA, .after = "mine_fac")

#then, bind the sheet general and sheet_sub_sites "below" each other
general <- bind_rows(general, sub_sites)

#detect duplicate coordinates
general <- general[!grepl(c("Smelter|Refinery"), general$mine_or_processing, ignore.case = TRUE),]
dupli <- filter(general, !is.na(latitude))[duplicated(na.omit(general$latitude)),]
dupli <- filter(general, latitude %in% dupli$latitude)[order(dupli$latitude),]
dupli <- dupli %>% select(., mine_fac, sub_site, latitude, longitude)


# table for Rmd output
DT::datatable(dupli)


```

<br> 

```{r , echo = FALSE, message = FALSE}

### check values per mine/material for one year vs next to check for potential typos, i.e. outliers in time series


# table for Rmd output
# DT::datatable()  

```

<br> 

```{r, echo = FALSE, message = FALSE}

### check for double counting between ores and concentrates


```

<br> 

```{r}



```

<br> 

```{r}

```

