---
title: "Coal coverage aggregated"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, error=TRUE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(rlang)
library(scales)
library(DT)

```

<br> 

```{r , echo = FALSE, message = FALSE}

### read files and load data

## harmonized data file (detailed data)
detailed <- read_rds("./03_intermediate/01_detailed_data/gaps_filled.rds")

# sheets from detailed data
general <- detailed$general
sheet_min <- detailed$minerals_ores_conce
sheet_com <- detailed$commodities

## national accounts

# get the latest file for national accounts from folder
source("./02_scripts/00_functions/lastfile.R")

lastfile <- my_lastfile("./01_input/05_other_data/", "data_converted")

nat_acc <- read_rds(lastfile)

# nat_acc <- read_delim(
#   lastfile, 
#   delim = ";", 
#   col_types = cols(year = "i", unit_id = "c")
#   )


## IDs
mat_ids <- read_delim("./01_input/02_lists_and_concordance_tables/material_ids.csv", delim = ";")

source_ids <- read_delim("./01_input/02_lists_and_concordance_tables/source_ids.csv", delim = ";")

```


```{r , echo = FALSE, message = FALSE}

#get two tables: 
#one showing the coverage of aggregated coal produced per country
#one showing the coverage of aggregated coal produced globally, once with and once without china


#all coal-related material ids
ids <- mat_ids %>% filter(., material_category_2 == "coal & peat" & material_id != "F.pea") %>%
  select(material_id)


#only include the national account numbers for coal, and aggregate them for every category of coal
nat_acc <- nat_acc %>%
  filter(material_id %in% ids[[1]] & year > 1999) %>%
  select(c(alphanumiso, year, value)) %>%
  group_by(alphanumiso, year) %>% 
  summarize(value = sum(value))

#write intermediate output for national accounts only related to coal, with all coal categories aggregated
write_delim(nat_acc, file = "./04_output/02_country_specific/nat_acc_coal.csv", delim =",")

# include country_ids in sheet_min
agg_min <- sheet_min %>%
  left_join(.,
            detailed$general %>%
              distinct(mine_fac, alphanumiso) %>%
              mutate(alphanumiso = ifelse(is.na(alphanumiso), "Other", alphanumiso))
  )

# aggregate, and filter for type_mineral == "Clean coal" only
agg_min <- agg_min %>%
  filter((type_mineral == "Clean coal")) %>%
  group_by(alphanumiso, year) %>%
  summarise(value = sum(value, na.rm = TRUE))


# join with national accounts
agg_min <- agg_min %>%
  full_join(.,
            nat_acc,
            by = c("alphanumiso", "year"),
            suffix = c(".det", ".nat")
  )


# share
agg_min <- agg_min %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2)
  )



# clean table
agg_min <- agg_min %>%
  filter(
    #!(year %in% c(2018, 2019)),
    !is.na(alphanumiso),
    !is.na(value.nat)
  )


# spread by country_id and material_id
coal_cov1 <- agg_min %>%
  mutate(share = percent(share, accuracy = 1)) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year)) %>%
  pivot_wider(., names_from = year, values_from = share) %>%
  # insert national totals again in order to rank properly (couldn't be kept, because of pivot function)
  left_join(., agg_min %>% filter(year == 2015) %>% select(-value.det, -share, -year)) %>%
  arrange(desc(value.nat))

# table for Rmd output
datatable(coal_cov1, rownames = FALSE, caption = "Relative coverage by country")


# spread by global totals for coal aggregated
coal_cov2 <- agg_min %>%
  group_by(year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2),
    #share = percent(share, accuracy = 1)
  ) %>%
  #select(-value.det, -value.nat) %>%
  arrange(desc(year)) 


# spread by global totals without china for coal aggregated
coal_cov3 <- agg_min %>%
  filter(., alphanumiso != "CHN156") %>%
  group_by(year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share_wo_china = value.det / value.nat,
    share_wo_china = round(share_wo_china, digits = 2),
    share_wo_china = percent(share_wo_china, accuracy = 1)
  ) %>%
  select(-value.det, -value.nat) %>%
  arrange(desc(year)) 


#join the table for global coverage with the table for global coverage without china
coal_cov4 <- left_join(coal_cov2, coal_cov3, by = "year")

# table for Rmd output
datatable(coal_cov4, rownames = FALSE, caption = "Relative coverage of global total, share is global total, share_wo_china is global total without China", options = list(columnDefs = list(list(className = 'dt-center', targets = 0:2))))

# line chart for Rmd output

# spread by global totals for coal aggregated
coal_cov_plot_global <- agg_min %>%
  group_by(year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share = value.det / value.nat,
    share = round(share, digits = 2), 
    global_or_wo_china = "global")


# spread by global totals without china for coal aggregated
coal_cov_plot_wo_china <- agg_min %>%
  filter(., alphanumiso != "CHN156") %>%
  group_by(year) %>%
  summarise(value.det = sum(value.det, na.rm = TRUE), value.nat = sum(value.nat, na.rm = TRUE)) %>%
  mutate(
    share_wo_china = value.det / value.nat,
    share_wo_china = round(share_wo_china, digits = 2),
    global_or_wo_china = "wo_china")

#combine the two dfs
coal_cov_plot <- bind_rows(coal_cov_plot_global, coal_cov_plot_wo_china)
coal_cov_plot$share <- coalesce(coal_cov_plot$share , coal_cov_plot$share_wo_china)

ggplot(coal_cov_plot, aes(x=year, y=share, group=global_or_wo_china)) +
  geom_line(aes(linetype=global_or_wo_china, color=global_or_wo_china), size = 1.5)+
  geom_point(aes(color=global_or_wo_china))+
  theme(legend.position="top") + 
  ylim(0, 1)

```


```{r , echo = FALSE, message = FALSE}

#create table with national coal accounts of all countries 
national_production_coal <- nat_acc %>% 
  pivot_wider(names_from = year, values_from = value) %>%
  arrange(desc(`2015`)) %>% 
  #join the coverage for the year 2015 to the dataframe
  left_join(., select(coal_cov1, alphanumiso,`2015`), by = "alphanumiso") %>%
  rename(., `coverage_2015` = `2015.y`, 
         `2015`= `2015.x`)

national_production_coal <- national_production_coal[,order(c(1,ncol(national_production_coal),c(seq(ncol(national_production_coal)-1,2,by=-1))))]



# table for Rmd output
datatable(national_production_coal, rownames = FALSE, caption = "Total national coal production, ordered by 2015 production", options = list(columnDefs = list(list(className = 'dt-center', targets = 0:ncol(national_production_coal)-1))))

```

<br>

```{r , echo = FALSE, message = FALSE}
## build heatmap of the coverage per country
plot_data <- agg_min %>%
  select(-value.det, -value.nat) %>%
  left_join(., agg_min %>% filter(year == 2015) %>% select(-value.det, -share, -year)) %>%
  filter(., value.nat >= 62344000) %>%
  arrange((value.nat))


plot_data$ord_countries <- factor(plot_data$alphanumiso, ordered=TRUE, levels = c("CAN124", "COL170", "KAZ398", "ZAF710", "RUS643", "IDN360", "AUS036", "IND356", "USA840", "CHN156"))

 
pdf(file = "./04_output/01_detailed_data/05_coverage/02_coal/coal_coverage_heatmap.pdf",   
    width = 16, 
    height = 8) 

ggplot(plot_data) +
  geom_tile(aes(x = year, y = ord_countries, fill = share)) +
  geom_text(aes(x = year, y = ord_countries, label = share)) +
  scale_fill_gradient2(low = "red", mid = "white", high = "steelblue")


dev.off()

```



```{r , echo = FALSE, message = FALSE, fig.cap = "Coverage of important metals and coal"}
# Create a plot that shows the coverage of important metals and coal 
# Iron ore, Copper, (Gold), Coal
cov_plot_group6 <- filter(cov_plot, min_ore_con %in% c("Me.Au", "Me.Cu", "O.Fe")) #gold, Copper, Iron ore

#get coal coverage, this relies on an output of the file 05_coverage_coal_aggregated.Rmd
coal_cov_plot <- coal_cov2 %>% 
  select(year, share) %>% 
  mutate(min_ore_con = "F.coal", 
         material_name = "Coal")


cov_plot_group6 <- bind_rows(cov_plot_group6, coal_cov_plot) %>%  filter(year < 2019)

pdf(file = "./04_output/01_detailed_data/05_coverage/01_general/coverage_important_materials.pdf",   
    width = 16, 
    height = 8) 

ggplot(cov_plot_group6, aes(x=year, y=share, group=material_name)) +
  geom_line(aes(linetype=material_name, color=material_name), size = 1.5)+
  ylab("Share of global total") + 
  xlab("Year") +
  #geom_point(aes(color=material_name))+
  theme(legend.position="top") + 
  ylim(0, 1)

dev.off()

```

