---
title: "Coverage total material"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, error=TRUE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(rlang)
library(scales)
library(DT)

```

<br> 

```{r , echo = FALSE, message = FALSE}

## read files

# harmonized data file
detailed <- read_rds("./detailed_data/03_intermediate/all_tables_converted.rds")

# sheets from detailed data
general <- detailed$general
sheet_waste <- detailed$waste


# IDs
mat_ids <- read_delim("./detailed_data/01_input/02_lists_and_concordance_tables/material_ids.csv", delim = ";")


```

<br> 

### Waste rock / Overburden / Total material
```{r message=FALSE, , echo=FALSE}

tot_mat <- sheet_waste %>% 
  filter(!is.na(total_material)) %>%
  distinct(mine_fac) %>%
  union(.,
    sheet_waste %>% 
      filter(waste_type == "Waste rock") %>%
      distinct(mine_fac)
    )



mines <- general %>%
  filter(mine_fac %in% tot_mat$mine_fac) %>%
  select(country, commodities_products, mine_fac, mining_facility_types, state, region, province, district) %>%
  arrange(country, commodities_products, mining_facility_types)



# table for Rmd output
datatable(mines, rownames = FALSE, caption = "Mines with info on Waste rock / Overburden / Total material")



# table for Rmd output
datatable(
  mines %>%
    group_by(commodities_products) %>%
    summarise(n = n()), 
  rownames = FALSE, caption = "Number of mines with above info, by commodities")



# table for Rmd output
datatable(
  mines %>%
    filter(!is.na(mining_facility_types)) %>%
    group_by(mining_facility_types) %>%
    summarise(n = n()) %>%
    ungroup() %>%
    arrange(desc(n)), 
  rownames = FALSE, caption = "Number of mines with above info, by mining types")


# mines which fulfil the above criteria, have open pit and underground mining, and specify "Open pit" for waste rock in sheet_waste
datatable(
  mines %>%
    filter(grepl("Open pit", mining_facility_types)) %>%
    filter(grepl("Underground", mining_facility_types)) %>%
    filter(!mining_facility_types %in% c("Open pit", "Open Pit")) %>%
    filter(
      mine_fac %in% (sheet_waste %>%
                       filter(type_mining == "Open pit") %>%
                       distinct(mine_fac) %>%
                       pull()
                     )
    ), 
  rownames = FALSE, caption = "Mines with above info, which have open pit + underground mining, and specify 'Open pit' for waste rock in sheet_waste")



# table for Rmd output
datatable(
  mines %>%
    filter(!is.na(country)) %>%
    group_by(country) %>%
    summarise(n = n()) %>%
    ungroup() %>%
    arrange(desc(n)), 
  rownames = FALSE, caption = "Number of mines with above info, by country")



```

<br> 

### Coal
```{r , echo = FALSE, message = FALSE}

coal <- general %>%
  filter(grepl("coal|Coal", commodities_products)) %>%
  select(country, commodities_products, mine_fac, mining_facility_types, state, region, province, district) %>%
  arrange(country, commodities_products, mining_facility_types)


# table for Rmd output
datatable(coal, rownames = FALSE, caption = "Coal mines (with any kind of info)")

# table for Rmd output
datatable(
  coal %>%
    filter(!is.na(country)) %>%
    group_by(country) %>%
    summarise(n = n()) %>%
    ungroup() %>%
    arrange(desc(n)), 
  rownames = FALSE, caption = "Number of mines with coal, by country")

# table for Rmd output
datatable(
  coal %>%
    filter(!is.na(mining_facility_types)) %>%
    group_by(mining_facility_types) %>%
    summarise(n = n()) %>%
    ungroup() %>%
    arrange(desc(n)), 
  rownames = FALSE, caption = "Number of mines with coal, by mining_types")


```

<br> 

```{r , echo = FALSE, message = FALSE}



```
